---
title: "Enrichment covid"
author: "Malassigne_Victor"
date: "11/18/2022"
output: 
  html_document:
    toc: yes
    toc_depth: 4
---

## 1 Library  
```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = T, fig.height=9, fig.width=9, fig.align="center")

if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if (!require('org.Hs.eg.db')) BiocManager::install('org.Hs.eg.db'); library('org.Hs.eg.db')
if (!require('AnnotationDbi')) BiocManager::install('AnnotationDbi'); library('AnnotationDbi')
if (!require('enrichplot')) BiocManager::install('enrichplot'); library('enrichplot')
if (!require('clusterProfiler')) BiocManager::install('clusterProfiler'); library('clusterProfiler')
if (!require('dplyr')) install.packages('dplyr'); library('dplyr')
if (!require('readr')) install.packages('readr'); library('readr')
if (!require('stringr')) install.packages('stringr'); library('stringr')
if (!require('factoextra')) install.packages('factoextra'); library('factoextra')
```

## 2 Import data
```{r, echo=FALSE, message=FALSE, warning=FALSE}
rm(list = ls())

name_DE_NR_R_HVG_all_VT1<- read.table("/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/name_DE_NR_R_HVG_all_VT1.txt")
name_DE_R_RP_HVG_all_VT2<- read.table("/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/name_DE_R_RP_HVG_all_VT2.txt")
load("/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/1.3_mat_pat_clean_final.rds") #ouverture de la svg
Metadata <- mat_pat_clean[737:743]
mat_pat_clean_sans_R_T<-mat_pat_clean[20:160,]
load("/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/HVG_scran.rds") #ouverture de la svg

my_palette = colorRampPalette(c("royalblue4", "lightskyblue3", "white", "lightsalmon3","darkred"))(n = 256)
```

<!-- ## 3 Enrichment -->
<!-- ### 3.1 KEGG -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- geneListEntrez = mapIds(org.Hs.eg.db,  -->
<!--                         keys=name_DE_NR_R_HVG_all[,1],  -->
<!--                         column="ENTREZID",  -->
<!--                         keytype="SYMBOL",  -->
<!--                         multiVals="first") -->

<!-- Kres <- enrichKEGG(gene          = geneListEntrez, -->
<!--                    organism      = "hsa", -->
<!--                    pAdjustMethod = "BH",  -->
<!--                    minGSSize     = 3, -->
<!--                    pvalueCutoff  = 0.05, # slider -->
<!--                    qvalueCutoff  = 0.05) # slider -->

<!-- # Kresmat = as.matrix(Kres[]) -->

<!-- barplot(Kres, showCategory=15, order=T) + ggtitle("Barplot of functional enrichment by KEGG") -->
<!-- dotplot(Kres, showCategory=15) + ggtitle("Dotplot of functional enrichment by KEGG") -->
<!-- ``` -->

<!-- ### 3.2 GO -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- geneListEnsembl= mapIds(org.Hs.eg.db,  -->
<!--                         keys=name_DE_NR_R_HVG_all[,1],  -->
<!--                         column="ENSEMBL",  -->
<!--                         keytype="SYMBOL",  -->
<!--                         multiVals="first") -->

<!-- enrichedRes_GO  <- enrichGO( -->
<!--   gene          = geneListEnsembl, -->
<!--   keyType       = "ENSEMBL", -->
<!--   OrgDb         = org.Hs.eg.db, -->
<!--   ont           = "BP", -->
<!--   pAdjustMethod = "BH",  -->
<!--   minGSSize     = 3, -->
<!--   pvalueCutoff  = 0.05, # slider -->
<!--   qvalueCutoff  = 0.05, # slider -->
<!--   readable      = TRUE) -->

<!-- # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!-- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle("Barplot of functional enrichment by GO") -->
<!-- dotplot(enrichedRes_GO, showCategory=15) + ggtitle("Dotplot of functional enrichment by GO") -->
<!-- ``` -->

<!-- ### 3.3 Reactom_PA -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- geneListEntrez_PA = mapIds(org.Hs.eg.db,  -->
<!--                         keys=name_DE_NR_R_HVG_all[,1],  -->
<!--                         column="ENTREZID",  -->
<!--                         keytype="SYMBOL",  -->
<!--                         multiVals="first") -->

<!-- enrichedRes_GS <- enrichPathway(gene          = geneListEntrez_PA, -->
<!--                                 organism      = 'human', -->
<!--                                 pAdjustMethod = "BH",  -->
<!--                                 minGSSize     = 3, -->
<!--                                 pvalueCutoff  = 0.05, # slider -->
<!--                                 qvalueCutoff  = 0.05) # slider -->

<!-- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle("Barplot of functional enrichment by REACTOM_PA") -->
<!-- dotplot(enrichedRes_GS, showCategory=15) + ggtitle("Dotplot of functional enrichment by REACTOM_PA") -->
<!-- ``` -->

## 4 Gene set IFN with visualization by PCA  
  
2 gene set =  
- REACTOME_INTERFERON_SIGNALING : 308 genes  
http://www.gsea-msigdb.org/gsea/msigdb/human/geneset/REACTOME_INTERFERON_SIGNALING.html  
- WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_INTERFERON_INDUCTION : 33 genes  
http://www.gsea-msigdb.org/gsea/msigdb/human/geneset/WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_INTERFERON_INDUCTION.html  
  
### 4.1 Set REACTOME_INTERFERON_SIGNALING
```{r, echo=FALSE, message=FALSE, warning=FALSE}
a <- read_tsv('/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/REACTOME_INTERFERON_SIGNALING.v2022.1.Hs.tsv')
members <- a[19,2]
members <- str_split(members, ',')
members <- as.data.frame(members[[1]])


inter <- intersect(members$`members[[1]]`, colnames(mat_pat_clean[1:736]))
mat_IFN <- mat_pat_clean[,match(inter, colnames(mat_pat_clean))] 
mat_IFN <- cbind(Metadata, mat_IFN)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter), " sont dans le jeu de donnée"))

inter_DE_VT1 <- intersect(members$`members[[1]]`, name_DE_NR_R_HVG_all_VT1$name_DE_NR_R_HVG_all)
mat_inter <- mat_pat_clean[,match(inter_DE_VT1, colnames(mat_pat_clean))] 
mat_IFN_DE_VT1 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter_DE_VT1), " sont dans les genes DE à VT1"))

mat_DE_VT1 <- mat_pat_clean[,match(name_DE_NR_R_HVG_all_VT1$name_DE_NR_R_HVG_all, colnames(mat_pat_clean))]
ma<- colnames(mat_DE_VT1) %in% colnames(mat_inter)
mat_inter <- mat_DE_VT1[,ma==F]
mat_no_IFN_DE_VT1 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(name_DE_NR_R_HVG_all_VT1)), " gènes du DE à VT1, ", length(colnames(mat_inter)), " ne sont pas dans le gene set IFN"))

inter_DE_VT2 <- intersect(members$`members[[1]]`, name_DE_R_RP_HVG_all_VT2$name_DE_NR_R_HVG_all)
mat_inter <- mat_pat_clean[,match(inter_DE_VT2, colnames(mat_pat_clean))] 
mat_IFN_DE_VT2 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter_DE_VT2), " sont dans les genes DE à VT2"))

mat_DE_VT2 <- mat_pat_clean[,match(name_DE_R_RP_HVG_all_VT2$name_DE_NR_R_HVG_all, colnames(mat_pat_clean))]
ma<- colnames(mat_DE_VT2) %in% colnames(mat_inter)
mat_inter <- mat_DE_VT2[,ma==F]
mat_no_IFN_DE_VT2 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(name_DE_R_RP_HVG_all_VT2)), " gènes du DE à VT2, ", length(colnames(mat_inter)), " ne sont pas dans le gene set IFN"))

## PCA VT1 gene IFN-------------------------------------------------------------
print("PCA VT1 gene IFN")

ma<-mat_IFN$real_time_point %in% "VT1"
mat<- mat_IFN[ma==T,]
ma<-mat_IFN$real_time_point %in% "T"
mat_T<-mat_IFN[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur VT1 gène IFN")

### gene DE VT1 IFN ###
print("gene DE VT1 IFN")

ma<-mat_IFN_DE_VT1$real_time_point %in% "VT1"
mat<- mat_IFN_DE_VT1[ma==T,]
ma<-mat_IFN_DE_VT1$real_time_point %in% "T"
mat_T<-mat_IFN_DE_VT1[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT1 gène IFN")

### gene DE VT1 not gene set IFN ###
print("gene DE VT1 not gene set IFN ")

ma<-mat_no_IFN_DE_VT1$real_time_point %in% "VT1"
mat<- mat_no_IFN_DE_VT1[ma==T,]
ma<-mat_no_IFN_DE_VT1$real_time_point %in% "T"
mat_T<-mat_no_IFN_DE_VT1[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1 avec gène non présent dans le gene set IFN", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT1 avec gène non présent dans le gene set IFN")


## PCA VT2 gene IFN-------------------------------------------------------------
print( "PCA VT2 gene IFN")

ma<-mat_IFN$real_time_point %in% "VT2"
mat<- mat_IFN[ma==T,]
ma<-mat_IFN$real_time_point %in% "T"
mat_T<-mat_IFN[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT2", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F) +
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur VT2 gène IFN")

### gene DE VT2 IFN ###
print("gene DE VT2 IFN")

ma<-mat_IFN_DE_VT2$real_time_point %in% "VT2"
mat<- mat_IFN_DE_VT2[ma==T,]
ma<-mat_IFN_DE_VT2$real_time_point %in% "T"
mat_T<-mat_IFN_DE_VT2[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur DE à VT2", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT2 gène IFN")

### gene DE VT2 not gene set IFN ###
print("gene DE VT2 not gene set IFN ")

ma<-mat_no_IFN_DE_VT2$real_time_point %in% "VT2"
mat<- mat_no_IFN_DE_VT2[ma==T,]
ma<-mat_no_IFN_DE_VT2$real_time_point %in% "T"
mat_T<-mat_no_IFN_DE_VT2[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT2 avec gène non présent dans le gene set IFN", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()

SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT2 avec gène non présent dans le gene set IFN")
```

### 4.2 Set WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_INTERFERON_INDUCTION
```{r, echo=FALSE, message=FALSE, warning=FALSE}
a <- read_tsv('/Users/victor/Documents/JM/NanoString/IFN_covid_nano/data/WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_INTERFERON_INDUCTION.v2022.1.Hs.tsv')
members <- a[19,2]
members <- str_split(members, ',')
members <- as.data.frame(members[[1]])


inter <- intersect(members$`members[[1]]`, colnames(mat_pat_clean[1:736]))
mat_IFN <- mat_pat_clean[,match(inter, colnames(mat_pat_clean))] 
mat_IFN <- cbind(Metadata, mat_IFN)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter), " sont dans le jeu de donnée"))

inter_DE_VT1 <- intersect(members$`members[[1]]`, name_DE_NR_R_HVG_all_VT1$name_DE_NR_R_HVG_all)
mat_inter <- mat_pat_clean[,match(inter_DE_VT1, colnames(mat_pat_clean))] 
mat_IFN_DE_VT1 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter_DE_VT1), " sont dans les genes DE à VT1"))

mat_DE_VT1 <- mat_pat_clean[,match(name_DE_NR_R_HVG_all_VT1$name_DE_NR_R_HVG_all, colnames(mat_pat_clean))]
ma<- colnames(mat_DE_VT1) %in% colnames(mat_inter)
mat_inter <- mat_DE_VT1[,ma==F]
mat_no_IFN_DE_VT1 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(name_DE_NR_R_HVG_all_VT1)), " gènes du DE à VT1, ", length(colnames(mat_inter)), " ne sont pas dans le gene set IFN"))

inter_DE_VT2 <- intersect(members$`members[[1]]`, name_DE_R_RP_HVG_all_VT2$name_DE_NR_R_HVG_all)
mat_inter <- mat_pat_clean[,match(inter_DE_VT2, colnames(mat_pat_clean))] 
mat_IFN_DE_VT2 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(members)), " gènes du gene set IFN, ", length(inter_DE_VT2), " sont dans les genes DE à VT2"))

mat_DE_VT2 <- mat_pat_clean[,match(name_DE_R_RP_HVG_all_VT2$name_DE_NR_R_HVG_all, colnames(mat_pat_clean))]
ma<- colnames(mat_DE_VT2) %in% colnames(mat_inter)
mat_inter <- mat_DE_VT2[,ma==F]
mat_no_IFN_DE_VT2 <- cbind(Metadata, mat_inter)
print(paste0("Sur les ", length(t(name_DE_R_RP_HVG_all_VT2)), " gènes du DE à VT2, ", length(colnames(mat_inter)), " ne sont pas dans le gene set IFN"))

## PCA VT1 gene IFN-------------------------------------------------------------
print("PCA VT1 gene IFN")

ma<-mat_IFN$real_time_point %in% "VT1"
mat<- mat_IFN[ma==T,]
ma<-mat_IFN$real_time_point %in% "T"
mat_T<-mat_IFN[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur VT1 gène IFN")

### gene DE VT1 IFN ###
print("gene DE VT1 IFN")

ma<-mat_IFN_DE_VT1$real_time_point %in% "VT1"
mat<- mat_IFN_DE_VT1[ma==T,]
ma<-mat_IFN_DE_VT1$real_time_point %in% "T"
mat_T<-mat_IFN_DE_VT1[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT1 gène IFN")

### gene DE VT1 not gene set IFN ###
print("gene DE VT1 not gene set IFN")

ma<-mat_no_IFN_DE_VT1$real_time_point %in% "VT1"
mat<- mat_no_IFN_DE_VT1[ma==T,]
ma<-mat_no_IFN_DE_VT1$real_time_point %in% "T"
mat_T<-mat_no_IFN_DE_VT1[ma==T,]
mat_VT1 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT1[,1:7]
mat_PCA<-mat_VT1[,8:length(mat_VT1)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT1 avec gène non présent dans le gene set IFN", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT1 avec gène non présent dans le gene set IFN")


## PCA VT2 gene IFN-------------------------------------------------------------
print(" PCA VT2 gene IFN")

ma<-mat_IFN$real_time_point %in% "VT2"
mat<- mat_IFN[ma==T,]
ma<-mat_IFN$real_time_point %in% "T"
mat_T<-mat_IFN[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT2", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F) +
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur VT2 gène IFN")

### gene DE VT2 IFN ###
print("gene DE VT2 IFN")

ma<-mat_IFN_DE_VT2$real_time_point %in% "VT2"
mat<- mat_IFN_DE_VT2[ma==T,]
ma<-mat_IFN_DE_VT2$real_time_point %in% "T"
mat_T<-mat_IFN_DE_VT2[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur DE à VT2", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()


SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT2 gène IFN")

### gene DE VT2 not gene set IFN ###
print("gene DE VT2 not gene set IFN")

ma<-mat_no_IFN_DE_VT2$real_time_point %in% "VT2"
mat<- mat_no_IFN_DE_VT2[ma==T,]
ma<-mat_no_IFN_DE_VT2$real_time_point %in% "T"
mat_T<-mat_no_IFN_DE_VT2[ma==T,]
mat_VT2 <- rbind(mat_T, mat)

MataData_PCA<-mat_VT2[,1:7]
mat_PCA<-mat_VT2[,8:length(mat_VT2)]
mat_PCA<-scale(mat_PCA)
PCA <- prcomp(mat_PCA, scale. = F)
fviz_eig(PCA, main = "Variance par PC sur VT2 avec gène non présent dans le gene set IFN", addlabels = TRUE)
fviz_pca_var(PCA,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, # Avoid text overlapping
             select.var = list(contrib = 10),
             alpha.var="contrib") +
   theme_minimal()

SelectPCA <- as.data.frame(PCA$x)
mergeMetaAPC <- as.data.frame(cbind(SelectPCA, MataData_PCA))
label<- as.character(mergeMetaAPC$numero_patient)

ggplot(mergeMetaAPC, aes(x = PC1, y = PC2, color = REPONSE)) +
  geom_point() + 
  geom_text(label = label,
            nudge_x=0.7, 
            nudge_y=0.3,
            check_overlap=F)+
  scale_color_manual(breaks = c("NR","R","RP","T"),
                     values = c("darkorange","cornflowerblue","brown3","chartreuse4"))+
  labs(title="PCA sur DE à VT2 avec gène non présent dans le gene set IFN")
```
# UMAP
```{r}
library(umap)
mat <- mat_pat_clean[,1:736]
meta <- mat_pat_clean[,737:length(mat_pat_clean)]
umap <- umap(scale(mat))

Selectumap <- as.data.frame(umap$layout)
mergeMetaumap <- as.data.frame(cbind(Selectumap, meta))

ggplot(mergeMetaumap, aes(x = V1, y = V2, color = real_time_point)) +
  geom_point() 

ma <- mat_pat_clean$real_time_point %in% "VT2"
mat_VT1 <- mat_pat_clean[ma==T,]
ma <- mat_pat_clean$REPONSE %in% "T"
mat_T <- mat_pat_clean[ma==T,]
mat_VT1_T <- rbind(mat_VT1, mat_T)

mat <- mat_VT1_T[,1:736]
meta <- mat_VT1_T[,737:length(mat_VT1_T)]
umap <- umap(scale(mat))

Selectumap <- as.data.frame(umap$layout)
mergeMetaumap <- as.data.frame(cbind(Selectumap, meta))

ggplot(mergeMetaumap, aes(x = V1, y = V2, color = REPONSE)) +
  geom_point() 
```

