---
title: "Unique gene VT NR/R/RP"
author: "Malassigne_Victor"
date: "5/31/2023"
output: 
  html_document:
    number_sections: true
    toc: yes
    toc_depth: 3
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(openxlsx)
library(ggpubr)
library(rstatix)
library(cowplot)
library(readxl)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
load("~/Documents/JM/NanoString/IFN_covid_nano/data/1.3_mat_pat_clean_final.rds") #ouverture de la svg

T_F <- mat_pat_clean$REPONSE %in% c("T", "R", "RP", "NR")
mat_pat_clean <- mat_pat_clean[T_F == T,]
```


# Liste de gènes

3 listes de gènes qui les gènes gènes unique à VT1 & VT2 (Venn)
```{r, echo=FALSE, message=FALSE, warning=FALSE}
gene_VT1_NR_R_unique <- c("ALPL",    "C3AR1",   "CARD17",  "CD22",    "CD45RA",  "DEFA4",   "FAM30A",  "IFI27",   "LILRA3", "LILRA5",  "LTF",     "NT5E",    "CASP1",   "IL15",    "IRF9",    "TMEM140") 

gene_VT2_R_RP_unique <- c( "C2",       "CCL8",     "CD19" ,    "FCGR1A/B", "GBP5"   ,  "IDO1" ,    "IL1R2"  ,  "MAFB",  "NTNG2"   , "SOCS1"   , "TAP1"  ,   "TLR7",     "BLK" ,     "KLRB1",    "SPIB"  ,   "TCL1A")

gene_VT1_T_NR_unique <- "LILRA3"
```

## Gènes unique à VT1 issu du DE TvsNR
```{r, echo=FALSE, message=FALSE, warning=FALSE}
T_F <- colnames(mat_pat_clean) %in% gene_VT1_T_NR_unique
mat_macro <- cbind(mat_pat_clean[, T_F == T], mat_pat_clean[,737 : 743])

mat_macro <- rename(mat_macro, "LILRA3" = `mat_pat_clean[, T_F == T]`)

ggplot(mat_macro, aes(x = REPONSE, y = LILRA3, fill = real_time_point)) +
  geom_violin()
```

## Gènes unique à VT1 issu du DE NRvsR
```{r, echo=FALSE, message=FALSE, warning=FALSE}
T_F <- colnames(mat_pat_clean) %in% gene_VT1_NR_R_unique
mat_macro <- cbind(mat_pat_clean[, T_F == T], mat_pat_clean[,737 : 743])

for (i in 1:16) {
  print(ggplot(mat_macro, aes(x = REPONSE, y = mat_macro[,i], fill = real_time_point)) +
          geom_violin()+
          labs(y = names(mat_macro[i]) ))
}
```

## Gènes unique à VT2 issu du DE RvsRP
```{r, echo=FALSE, message=FALSE, warning=FALSE}
T_F <- colnames(mat_pat_clean) %in% gene_VT2_R_RP_unique
mat_macro <- cbind(mat_pat_clean[, T_F == T], mat_pat_clean[,737 : 743])

for (i in 1:16) {
  print(ggplot(mat_macro, aes(x = REPONSE, y = mat_macro[,i], fill = real_time_point)) +
          geom_violin()+
          labs(y = names(mat_macro[i]) ))
}
```













